### ISSUE TITLE
Do not download large files such as FLAC and MP3

### ISSUE THREAD

**Issue by DamonHD** [tb0hdan/domains#27] opened 2024-02-15 11:45 UTC
Downloading these places a significant load on servers, and most are not going to contain URL metadata of use to the project.

This is probably true of image files too.

At least please explicitly describe a suitable robots.txt User-agent name to stop the tool scraping inappropriate sites/subtrees.

Rgds

Damon

**Comment by tb0hdan** [comment] 2024-02-15 15:42
Hi,

Is it GET /some/large/file.mp3 or just HEAD ?

Thanks

**Comment by DamonHD** [comment] 2024-02-15 16:36
GET

**Comment by tb0hdan** [comment] 2024-02-15 16:55
Got it, it's a duplicate of #28

**Closed** 2024-02-19 01:40 UTC
